---
host1:
    hostname: 192.168.99.158
    username: cisco
    password: cisco
    device_type: cisco_ios
    platform: ios
    global_delay_factor: 2

host2:
    hostname: 192.168.99.63
    username: cisco
    password: cisco
    device_type: cisco_ios
    platform: ios
    global_delay_factor: 2

# platform is what napalm uses for network drivers